# Generated by Django 3.2.7 on 2021-12-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='add_no',
            field=models.CharField(default='1w1', max_length=50),
            preserve_default=False,
        ),
    ]
