# Generated by Django 3.2.7 on 2022-01-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20220116_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
