# Generated by Django 3.2.7 on 2022-01-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
