# Generated by Django 3.2.7 on 2022-01-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_student_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
