# Generated by Django 3.2.7 on 2022-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
