# Generated by Django 3.2.7 on 2022-01-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='school.school'),
        ),
    ]
