# Generated by Django 3.2.7 on 2021-12-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_user'),
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.school'),
        ),
    ]
