# Generated by Django 3.2.7 on 2021-12-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_auto_20211220_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fee.month')),
            ],
        ),
    ]
