# Generated by Django 3.2.7 on 2021-12-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_user'),
        ('fee', '0003_feestruct'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestruct',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.classes'),
        ),
    ]
