# Generated by Django 3.2.7 on 2021-12-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_user'),
        ('fee', '0004_feestruct_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestruct',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classes'),
        ),
    ]
