# Generated by Django 3.2.7 on 2021-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0008_feeadvance_mop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeadvance',
            name='mop',
        ),
    ]
