# Generated by Django 3.2.7 on 2021-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_remove_feeadvance_mop'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesubmit',
            name='mop',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
