# Generated by Django 3.2.7 on 2021-12-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_add_no'),
        ('fee', '0010_feesubmit_mop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classes')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fee.month')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.school')),
            ],
        ),
    ]
