# Generated by Django 3.2.7 on 2021-12-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_add_no'),
        ('fee', '0011_feestructbymonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSubmitByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_no', models.IntegerField(default=0)),
                ('advanced_amount', models.IntegerField(default=0)),
                ('total_session_fee', models.IntegerField(default=0)),
                ('session_fee_submitted', models.IntegerField(default=0)),
                ('session_fee_left', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
