# Generated by Django 3.2.7 on 2022-01-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0012_feesubmitbymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructbymonth',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
