# Generated by Django 3.2.7 on 2022-01-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0013_alter_feestructbymonth_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructbymonth',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
