# Generated by Django 3.2.7 on 2022-01-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0015_feeconcession_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconcession',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
