# Generated by Django 3.2.7 on 2022-01-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0016_feeconcession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeconcession',
            name='concession_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
