# Generated by Django 3.2.7 on 2022-01-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0018_chequedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineNeftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_no', models.CharField(max_length=50)),
                ('pay_by', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('fee_submit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fee.feesubmit')),
            ],
        ),
    ]
