# Generated by Django 3.2.7 on 2022-01-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0020_feeconcession_fee_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeconcession',
            name='concession',
        ),
    ]
