# Generated by Django 3.2.7 on 2022-01-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0021_remove_feeconcession_concession'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesubmit',
            name='txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
