# Generated by Django 3.2.7 on 2022-01-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0024_alter_feesubmit_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedetails',
            name='fee_submit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_cheque', to='fee.feesubmit'),
        ),
    ]
