# Generated by Django 3.2.7 on 2022-01-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_student_school'),
        ('fee', '0026_alter_onlineneftdetails_fee_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedFeeSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('delete_date', models.DateField(auto_now=True)),
                ('submit_date', models.DateField()),
                ('mop', models.CharField(default='Cash', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
