# Generated by Django 3.2.7 on 2022-01-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0027_deletedfeesubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedOnlineNeftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_no', models.CharField(max_length=50)),
                ('pay_by', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('fee_submit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_online', to='fee.deletedfeesubmit')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedChequeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=50)),
                ('issued_by', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField()),
                ('fee_submit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_cheque', to='fee.deletedfeesubmit')),
            ],
        ),
    ]
