# Generated by Django 3.2.7 on 2022-01-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_classes_class_no'),
        ('fee', '0030_auto_20220119_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
