# Generated by Django 3.2.7 on 2022-01-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0032_auto_20220125_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
