# Generated by Django 3.2.7 on 2022-02-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_classes_class_no'),
        ('fee', '0034_feesubmit_memo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructbymonth',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
        ),
    ]
