# Generated by Django 3.2.7 on 2022-02-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0035_alter_feestructbymonth_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscfee',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
