# Generated by Django 3.2.7 on 2022-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0036_miscfee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscfee',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
