# Generated by Django 3.2.7 on 2022-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0037_miscfee_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedetails',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chequedetails',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deletedchequedetails',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deletedchequedetails',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deletedonlineneftdetails',
            name='pay_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deletedonlineneftdetails',
            name='utr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onlineneftdetails',
            name='pay_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onlineneftdetails',
            name='utr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
